Pep8 and python2 fixed
rimek/fatek-fbs-lib pull request #9
Opened 2017-02-22 09:47 UTC by sih4sing5hong5

The environment of tests is ok in [travis](https://travis-ci.org/i3thuan5/fatek-fbs-lib).
There is [coverage](https://coveralls.io/builds/10270402), too.

2017-02-22 10:04 UTC, netrounds-rimek commented
ok, so maybe merge here stuff you did in the https://github.com/rimek/fatek-fbs-lib/issues/8 and close it, so there will be only one PR

2017-02-22 10:11 UTC, netrounds-rimek requested changes

2017-02-22 10:11 UTC, netrounds-rimek commented on fatek/target.py
> +        return (
no, revert it

2017-02-22 10:11 UTC, netrounds-rimek commented on fatek/__init__.py
> -from .fatek import Fatek
I rely on that in my code, which uses this lib

2017-02-22 10:11 UTC, netrounds-rimek commented on fatek/target.py
> +        if (
no, revert it. If you want to simplify conditions, put they into separate variables. I find it hard to read

2017-02-22 10:11 UTC, netrounds-rimek commented on .travis.yml
> +- pip install pymodbus pyserial || pip install pymodbus3 pyserial
this is no good, as I commented on the other PR, there should be `install: "pip install -r requirements.txt"` here. And there is a way to set conditions in `requirements.txt` - look at this:
https://www.python.org/dev/peps/pep-0496/#id6

2017-02-22 10:11 UTC, netrounds-rimek commented on fatek/symbol.py
> +            result = any(
also revert it

2017-02-22 10:11 UTC, netrounds-rimek commented on requirements.txt
> +pymodbus
according to the https://www.python.org/dev/peps/pep-0496/ you can put conditions here
```
pymodbus3 == 1.0.0; python_version >= '3.0'
pymodbus; python_version <= 3.0
```
and pin the specific version of `pymodbus`

2017-02-22 10:46 UTC, sih4sing5hong5 commented on requirements.txt
> +pymodbus
Cool

2017-02-22 10:58 UTC, rimek commented
Looks good, did you check if its working in both python versions ?

2017-02-22 10:59 UTC, rimek requested changes

2017-02-22 10:59 UTC, rimek commented on fatek/__init__.py
> +Fatek
what is that ? :)

2017-02-22 10:59 UTC, rimek commented on fatek/tools.py
> +    print("#TODO console client")
without `from __future__ import print_function` this won't work in python2. You can also leave `pass` here for now

2017-02-23 00:09 UTC, sih4sing5hong5 commented on fatek/__init__.py
> +Fatek
```
$ flake8 . --exclude=venv
./fatek/__init__.py:1:1: F401 '.fatek.Fatek' imported but unused
```
Maybe `__all__` is better than it.

2017-02-23 00:40 UTC, sih4sing5hong5 commented
python 2/3 worked in my [travis](https://travis-ci.org/i3thuan5/fatek-fbs-lib/builds/204425742).
Could you manipulate code format remained ?

2017-02-23 21:03 UTC, merged